disabled_rules: # rule identifiers to exclude from running
#- trailing_whitespace
#- multiple_closures_with_trailing_closure
- identifier_name
- unused_closure_parameter
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- TopContributors/application/R.generated.swift
- TopContributors/components/thirdparty
line_length: 210
